export const data = [
  {
    id: "6",
    title: "Реконструкция",
    type_id: "2",
    type: "Здрав",
    municipality_id: "1",
    municipality: "Городской",
    stage_id: "10",
    stage: "Экс",
    builder_id: "61",
    builder_name: "ООО",
    construction_ready: 0,
    expluatation: "201",
    zk_type_id: "2",
    zk_type: "Го",
    is_camers: "1",
    is_dgpr: "1",
    dgprDateLastReport: "2023",
    startAt: "1980",
    dgprDateLastReportOverdueWeek: false,
    isDeviationsSG: false,
    isTotalConstructionReadyFactDeviation: false,
    isTotalCountPeopleFactDeviation: false,
    url: "http://",
    totalCountPeopleFact: 9,
    totalCountPeoplePlan: 744,
    totalConstructionReadyPlan: 100,
    totalConstructionReadyFact: 0,
  },
]
